-- CLI Properties
SET linesize 300;
SET pagesize 300;

COLUMN BookName FORMAT A30;
COLUMN Author FORMAT A30;
COLUMN Lang FORMAT A13;



COLUMN Book_Name FORMAT A10;
COLUMN AUTHOR FORMAT A10;
COLUMN Language FORMAT A10;




COLUMN UserName FORMAT A20;
COLUMN Email FORMAT A30;